vim.opt.tabstop = 4
vim.optsofttabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.hlsearch = false
vim.opt.hidden = true
vim.opt.errorbells = false
vim.opt.wrap = false
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME").. "/.config/nvim/undodir"
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.scrolloff = 12
vim.opt.encoding = "utf-8"
vim.opt.autoread = true
vim.opt.cmdheight = 1
vim.opt.termguicolors = true
vim.opt.cursorline = true
vim.opt.laststatus = 3
vim.opt.showtabline = 3
vim.opt.list = true
vim.opt.fillchars = {stl = "―", fold = "۰", diff = "·"}
vim.opt.listchars = {tab = "»·", trail = "·", eol = "¬"}
vim.g.mapleader = " "
